return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "vim",
        "lua",
        "vimdoc",
        "html",
        "css",
        "go",
        "python",
        "typescript",
        "javascript",
        "ruby",
        "php",
        "java",
        "kotlin",
        "scala",
        "c",
        "cpp",
        "c_sharp",
        "rust",
        "markdown",
        "json",
        "yaml",
        "toml",
        "make",
        "cmake",
        "sql",
        "gitignore",
      },
    },
  },
}
